In [1]:
import pandas as pd
df = pd.read_excel("../data/matrix.xlsx")

In [2]:
df.head()

,Date,Address,Location,Area,Total Area,Rooms,Land Area,Price
0,9 oktober 2023,SkÃ¥rby station 350,"Kareby, KungÃ¤lvs kommun",143 + 25 m²,168 m²,7 rum,2 303 mÂ² tomt,3 005 000 kr
1,5 oktober 2023,HÃ¶galidsgatan 3,"Centrum, KungÃ¤lvs kommun",103 + 103 m²,206 m²,5 rum,862 mÂ² tomt,3 800 000 kr
2,3 oktober 2023,KungÃ¤lvsvÃ¤gen 22,"Centralt, KungÃ¤lvs kommun",77 + 46 m²,123 m²,5 rum,1 548 mÂ² tomt,4 500 000 kr
3,2 oktober 2023,Ã„delstensvÃ¤gen 58,"Kode, KungÃ¤lvs kommun",123 m²,NaN,6 rum,379 mÂ² tomt,4 075 000 kr
4,27 september 2023,KantorvÃ¤gen 4,"BohuslÃ¤n, KungÃ¤lvs kommun",166 m²,NaN,6 rum,558 mÂ² tomt,3 625 000 kr

In [3]:
df.shape

(1973, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1973 entries, 0 to 1972
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1973 non-null   str
 1   Address     1972 non-null   str
 2   Location    1973 non-null   str
 3   Area        1943 non-null   str
 4   Total Area  1067 non-null   str
 5   Rooms       1921 non-null   str
 6   Land Area   1947 non-null   str
 7   Price       1973 non-null   str
dtypes: str(8)
memory usage: 123.4 KB

In [5]:
df.isna().sum()

Date            0
Address         1
Location        0
Area           30
Total Area    906
Rooms          52
Land Area      26
Price           0
dtype: int64

In [6]:
df.describe()

,Date,Address,Location,Area,Total Area,Rooms,Land Area,Price
count,1973,1972,1973,1943,1067,1921,1947,1973
unique,1422,1773,229,1096,250,11,1262,549
top,2 juni 2021,KungÃ¤lvsvÃ¤gen 22,"Ytterby, KungÃ¤lvs kommun",122 m²,178 m²,5 rum,362 mÂ² tomt,4 500 000 kr
freq,5,3,174,23,19,587,9,35

## Find how much data is missing

In [7]:
# Drop the "Total Area" column
df = df.drop(columns=["Total Area", "Address"])

# Count rows that have at least one missing value
rows_with_missing = df.isna().any(axis=1).sum()

# Calculate the percentage of rows with at least one missing value
percentage_missing = (rows_with_missing / len(df)) * 100

print(f"Rows with at least one missing value: {rows_with_missing}")
print(f"Percentage of total rows: {percentage_missing:.2f}%")

Rows with at least one missing value: 95
Percentage of total rows: 4.82%

In [9]:
df.shape

(1973, 6)